server:
  port: 8089
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:13306/hltz?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 10
#      maximum-pool-size: 20
#      idle-timeout: 600000
#      max-life-time: 1800000
#
#  jpa:
#    hibernate:
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#        # 下面配置开启后，会禁止将驼峰转为下划线
#        # physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    open-in-view: false
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true
#        # 控制是否可以基于程序中Entity的定义自动创建或者修改DB中表结构
#        hbm2ddl.auto: update
#        # 控制是否打印运行时的SQL语句与参数信息
#    show-sql: true