spring:
  config:
    name: hello-world
  profiles:
    active: druid
logging:
  level:
    root: INFO             # 根日志级别
    web: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

server:
  port: 8089